-- Lumen Eye Care — storage buckets (Sprint 0 follow-up).
-- The init migration creates tables but NOT buckets; this provisions them as
-- code so staging/prod stay in sync (CLAUDE.md security rules 6 & 7).
--
--   frames        — PUBLIC  read, admin write. Catalogue imagery (US-P0-01).
--   prescriptions — PRIVATE. Access via short-lived signed URLs generated by the
--                   secret-key client (bypasses RLS); these object policies are
--                   the defense-in-depth layer for any direct API access.
--
-- Idempotent: re-running (or running over manually-created buckets) is safe.

-- ---------------------------------------------------------------------------
-- Buckets
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'frames', 'frames', true,
  5242880, -- 5 MB ceiling (delivery budget is <100 KB/image; this is just a guard)
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'prescriptions', 'prescriptions', false,
  10485760, -- 10 MB
  array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- ---------------------------------------------------------------------------
-- Object policies (RLS is already enabled on storage.objects by Supabase).
-- Drop-then-create so the migration is re-runnable.
-- ---------------------------------------------------------------------------

-- frames: anyone may read; only admins may write/modify/delete.
drop policy if exists "frames public read" on storage.objects;
create policy "frames public read" on storage.objects
  for select using (bucket_id = 'frames');

drop policy if exists "frames admin write" on storage.objects;
create policy "frames admin write" on storage.objects
  for all
  using (bucket_id = 'frames' and public.is_admin())
  with check (bucket_id = 'frames' and public.is_admin());

-- prescriptions: object path is `<user_id>/<file>`. Owners may read/insert their
-- own folder; admins may do anything; no public access. Deletes are owner+admin.
drop policy if exists "prescriptions owner read" on storage.objects;
create policy "prescriptions owner read" on storage.objects
  for select using (
    bucket_id = 'prescriptions'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "prescriptions owner insert" on storage.objects;
create policy "prescriptions owner insert" on storage.objects
  for insert with check (
    bucket_id = 'prescriptions'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "prescriptions owner delete" on storage.objects;
create policy "prescriptions owner delete" on storage.objects
  for delete using (
    bucket_id = 'prescriptions'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "prescriptions admin all" on storage.objects;
create policy "prescriptions admin all" on storage.objects
  for all
  using (bucket_id = 'prescriptions' and public.is_admin())
  with check (bucket_id = 'prescriptions' and public.is_admin());
